// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type User struct {
	Id               *string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name             *string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Avatar           *string      `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	OfflineTime      *string      `protobuf:"bytes,4,opt,name=offlineTime" json:"offlineTime,omitempty"`
	CountryName      *string      `protobuf:"bytes,5,opt,name=countryName" json:"countryName,omitempty"`
	KingLisence      *KingLisence `protobuf:"bytes,6,opt,name=kingLisence" json:"kingLisence,omitempty"`
	Charges          []float64    `protobuf:"fixed64,7,rep,name=charges" json:"charges,omitempty"`
	IsNew            *bool        `protobuf:"varint,8,opt,name=isNew" json:"isNew,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *User) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

func (m *User) GetOfflineTime() string {
	if m != nil && m.OfflineTime != nil {
		return *m.OfflineTime
	}
	return ""
}

func (m *User) GetCountryName() string {
	if m != nil && m.CountryName != nil {
		return *m.CountryName
	}
	return ""
}

func (m *User) GetKingLisence() *KingLisence {
	if m != nil {
		return m.KingLisence
	}
	return nil
}

func (m *User) GetCharges() []float64 {
	if m != nil {
		return m.Charges
	}
	return nil
}

func (m *User) GetIsNew() bool {
	if m != nil && m.IsNew != nil {
		return *m.IsNew
	}
	return false
}

type KingLisence struct {
	Name              *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Have              *uint32  `protobuf:"varint,2,opt,name=have" json:"have,omitempty"`
	Remain            *int32   `protobuf:"varint,3,opt,name=remain" json:"remain,omitempty"`
	GiveWings         *uint32  `protobuf:"varint,4,opt,name=giveWings" json:"giveWings,omitempty"`
	AttackIncr        *float64 `protobuf:"fixed64,5,opt,name=attackIncr" json:"attackIncr,omitempty"`
	SpeedIncr         *float64 `protobuf:"fixed64,6,opt,name=speedIncr" json:"speedIncr,omitempty"`
	OfflineIncomeIncr *float64 `protobuf:"fixed64,7,opt,name=offlineIncomeIncr" json:"offlineIncomeIncr,omitempty"`
	InvadeListIncr    *uint32  `protobuf:"varint,8,opt,name=invadeListIncr" json:"invadeListIncr,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *KingLisence) Reset()                    { *m = KingLisence{} }
func (m *KingLisence) String() string            { return proto.CompactTextString(m) }
func (*KingLisence) ProtoMessage()               {}
func (*KingLisence) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *KingLisence) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *KingLisence) GetHave() uint32 {
	if m != nil && m.Have != nil {
		return *m.Have
	}
	return 0
}

func (m *KingLisence) GetRemain() int32 {
	if m != nil && m.Remain != nil {
		return *m.Remain
	}
	return 0
}

func (m *KingLisence) GetGiveWings() uint32 {
	if m != nil && m.GiveWings != nil {
		return *m.GiveWings
	}
	return 0
}

func (m *KingLisence) GetAttackIncr() float64 {
	if m != nil && m.AttackIncr != nil {
		return *m.AttackIncr
	}
	return 0
}

func (m *KingLisence) GetSpeedIncr() float64 {
	if m != nil && m.SpeedIncr != nil {
		return *m.SpeedIncr
	}
	return 0
}

func (m *KingLisence) GetOfflineIncomeIncr() float64 {
	if m != nil && m.OfflineIncomeIncr != nil {
		return *m.OfflineIncomeIncr
	}
	return 0
}

func (m *KingLisence) GetInvadeListIncr() uint32 {
	if m != nil && m.InvadeListIncr != nil {
		return *m.InvadeListIncr
	}
	return 0
}

type UserInfo struct {
	Name             *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Avatar           *string  `protobuf:"bytes,2,opt,name=avatar" json:"avatar,omitempty"`
	Speed            *float64 `protobuf:"fixed64,3,opt,name=speed" json:"speed,omitempty"`
	Attack           *float64 `protobuf:"fixed64,4,opt,name=attack" json:"attack,omitempty"`
	AttackCityNum    *uint32  `protobuf:"varint,5,opt,name=attackCityNum" json:"attackCityNum,omitempty"`
	OwnCityNum       *uint32  `protobuf:"varint,6,opt,name=ownCityNum" json:"ownCityNum,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return ""
}

func (m *UserInfo) GetSpeed() float64 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *UserInfo) GetAttack() float64 {
	if m != nil && m.Attack != nil {
		return *m.Attack
	}
	return 0
}

func (m *UserInfo) GetAttackCityNum() uint32 {
	if m != nil && m.AttackCityNum != nil {
		return *m.AttackCityNum
	}
	return 0
}

func (m *UserInfo) GetOwnCityNum() uint32 {
	if m != nil && m.OwnCityNum != nil {
		return *m.OwnCityNum
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "msg.User")
	proto.RegisterType((*KingLisence)(nil), "msg.KingLisence")
	proto.RegisterType((*UserInfo)(nil), "msg.UserInfo")
}

var fileDescriptor3 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4f, 0xf3, 0x30,
	0x0c, 0x87, 0x95, 0xfd, 0x9f, 0xfb, 0x66, 0x2f, 0x0b, 0x02, 0x85, 0xdb, 0x34, 0x09, 0x69, 0xa7,
	0x1d, 0xf8, 0x0a, 0x9c, 0x26, 0xd0, 0x4e, 0x20, 0xce, 0x51, 0xe7, 0x76, 0xd1, 0x68, 0x32, 0x25,
	0x69, 0xa7, 0x7d, 0x1c, 0x2e, 0x7c, 0x4e, 0x12, 0x97, 0x32, 0xc4, 0xd1, 0x8f, 0x6d, 0xf9, 0xf1,
	0x0f, 0xa0, 0xf6, 0xe8, 0xd6, 0x47, 0x67, 0x83, 0x15, 0xfd, 0xca, 0x97, 0xcb, 0x0f, 0x06, 0x83,
	0xd7, 0xc8, 0x04, 0x40, 0x4f, 0xef, 0x24, 0x5b, 0xb0, 0xd5, 0x54, 0xfc, 0x83, 0x81, 0x51, 0x15,
	0xca, 0x1e, 0x55, 0x33, 0x18, 0xa9, 0x46, 0x05, 0xe5, 0x64, 0x9f, 0xea, 0x6b, 0xc8, 0x6c, 0x51,
	0xbc, 0x6b, 0x83, 0x2f, 0x3a, 0x0e, 0x0d, 0x3a, 0x98, 0xdb, 0xda, 0x04, 0x77, 0xde, 0xa6, 0xcd,
	0x21, 0xc1, 0x7b, 0xc8, 0x0e, 0xda, 0x94, 0xcf, 0xda, 0xa3, 0xc9, 0x51, 0x8e, 0x22, 0xcc, 0x1e,
	0xae, 0xd6, 0xf1, 0xee, 0xfa, 0xe9, 0xc2, 0xc5, 0x7f, 0x18, 0xe7, 0x7b, 0xe5, 0x4a, 0xf4, 0x72,
	0xbc, 0xe8, 0xaf, 0x98, 0xe0, 0x30, 0xd4, 0x7e, 0x8b, 0x27, 0x39, 0x89, 0x1b, 0x93, 0xe5, 0x27,
	0x83, 0xec, 0xf7, 0x7c, 0xa7, 0xf7, 0x23, 0xbb, 0x57, 0x4d, 0x2b, 0xcb, 0x93, 0xac, 0xc3, 0x4a,
	0x69, 0x43, 0xb2, 0x43, 0x31, 0x87, 0x69, 0xa9, 0x1b, 0x7c, 0x8b, 0xeb, 0x9e, 0x54, 0xb9, 0x88,
	0xaf, 0xaa, 0x10, 0x54, 0x7e, 0xd8, 0x98, 0xdc, 0x91, 0x29, 0x4b, 0x63, 0xfe, 0x88, 0xb8, 0x23,
	0x34, 0x22, 0x74, 0x07, 0xf3, 0xef, 0x37, 0x23, 0xb4, 0x15, 0x52, 0x6b, 0x4c, 0xad, 0x5b, 0x98,
	0x69, 0xd3, 0xa8, 0x1d, 0x46, 0xa3, 0x40, 0x3c, 0x89, 0xf2, 0xa5, 0x83, 0x49, 0xca, 0x72, 0x63,
	0x0a, 0xfb, 0x47, 0xf2, 0x92, 0x61, 0x9b, 0x69, 0xfc, 0x90, 0xee, 0x91, 0x25, 0xa3, 0x36, 0x29,
	0x91, 0x22, 0x13, 0x37, 0xc0, 0xdb, 0xfa, 0x51, 0x87, 0xf3, 0xb6, 0xae, 0xc8, 0x92, 0xcc, 0xed,
	0xc9, 0x74, 0x2c, 0x69, 0xf2, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0xd8, 0x03, 0x5b, 0xd2,
	0x01, 0x00, 0x00,
}
