// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// id: 2
type Login struct {
	User             *User  `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Login) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// id: 24
type LoginRequest struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	DeviceId         *uint32 `protobuf:"varint,2,req,name=deviceId" json:"deviceId,omitempty"`
	Version          *uint32 `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LoginRequest) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *LoginRequest) GetDeviceId() uint32 {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return 0
}

func (m *LoginRequest) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Login)(nil), "msg.Login")
	proto.RegisterType((*LoginRequest)(nil), "msg.loginRequest")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0xe2, 0x2a, 0x2d,
	0x4e, 0x2d, 0x82, 0x08, 0x28, 0xa9, 0x71, 0xb1, 0xfa, 0x80, 0xe4, 0x85, 0x64, 0xb9, 0x58, 0x40,
	0xc2, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xdc, 0x46, 0x9c, 0x7a, 0xb9, 0xc5, 0xe9, 0x7a, 0xa1, 0xc5,
	0xa9, 0x45, 0x41, 0x60, 0x61, 0xa5, 0x28, 0x2e, 0x1e, 0xb0, 0x39, 0x41, 0xa9, 0x85, 0xa5, 0xa9,
	0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x60, 0xf5, 0x9c, 0x41, 0x10,
	0x8e, 0x90, 0x14, 0x17, 0x47, 0x4a, 0x6a, 0x59, 0x66, 0x72, 0xaa, 0x67, 0x8a, 0x04, 0x93, 0x02,
	0x93, 0x06, 0x6f, 0x10, 0x9c, 0x2f, 0x24, 0xc1, 0xc5, 0x5e, 0x96, 0x5a, 0x54, 0x9c, 0x99, 0x9f,
	0x27, 0xc1, 0x0c, 0x96, 0x82, 0x71, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2a, 0xe8, 0x2e, 0x25,
	0xa2, 0x00, 0x00, 0x00,
}
