// Code generated by protoc-gen-go.
// source: spare.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Spare0 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare0) Reset()                    { *m = Spare0{} }
func (m *Spare0) String() string            { return proto.CompactTextString(m) }
func (*Spare0) ProtoMessage()               {}
func (*Spare0) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type Spare1 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare1) Reset()                    { *m = Spare1{} }
func (m *Spare1) String() string            { return proto.CompactTextString(m) }
func (*Spare1) ProtoMessage()               {}
func (*Spare1) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type Spare2 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare2) Reset()                    { *m = Spare2{} }
func (m *Spare2) String() string            { return proto.CompactTextString(m) }
func (*Spare2) ProtoMessage()               {}
func (*Spare2) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type Spare3 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare3) Reset()                    { *m = Spare3{} }
func (m *Spare3) String() string            { return proto.CompactTextString(m) }
func (*Spare3) ProtoMessage()               {}
func (*Spare3) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

type Spare4 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare4) Reset()                    { *m = Spare4{} }
func (m *Spare4) String() string            { return proto.CompactTextString(m) }
func (*Spare4) ProtoMessage()               {}
func (*Spare4) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

type Spare5 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare5) Reset()                    { *m = Spare5{} }
func (m *Spare5) String() string            { return proto.CompactTextString(m) }
func (*Spare5) ProtoMessage()               {}
func (*Spare5) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

type Spare6 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare6) Reset()                    { *m = Spare6{} }
func (m *Spare6) String() string            { return proto.CompactTextString(m) }
func (*Spare6) ProtoMessage()               {}
func (*Spare6) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

type Spare7 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare7) Reset()                    { *m = Spare7{} }
func (m *Spare7) String() string            { return proto.CompactTextString(m) }
func (*Spare7) ProtoMessage()               {}
func (*Spare7) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

type Spare8 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare8) Reset()                    { *m = Spare8{} }
func (m *Spare8) String() string            { return proto.CompactTextString(m) }
func (*Spare8) ProtoMessage()               {}
func (*Spare8) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

type Spare9 struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Spare9) Reset()                    { *m = Spare9{} }
func (m *Spare9) String() string            { return proto.CompactTextString(m) }
func (*Spare9) ProtoMessage()               {}
func (*Spare9) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func init() {
	proto.RegisterType((*Spare0)(nil), "msg.Spare0")
	proto.RegisterType((*Spare1)(nil), "msg.Spare1")
	proto.RegisterType((*Spare2)(nil), "msg.Spare2")
	proto.RegisterType((*Spare3)(nil), "msg.Spare3")
	proto.RegisterType((*Spare4)(nil), "msg.Spare4")
	proto.RegisterType((*Spare5)(nil), "msg.Spare5")
	proto.RegisterType((*Spare6)(nil), "msg.Spare6")
	proto.RegisterType((*Spare7)(nil), "msg.Spare7")
	proto.RegisterType((*Spare8)(nil), "msg.Spare8")
	proto.RegisterType((*Spare9)(nil), "msg.Spare9")
}

func init() { proto.RegisterFile("spare.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 75 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0x48, 0x2c,
	0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xe2, 0xe0, 0x62,
	0x0b, 0x06, 0x89, 0x19, 0xc0, 0x59, 0x86, 0x70, 0x96, 0x11, 0x9c, 0x65, 0x0c, 0x67, 0x99, 0xc0,
	0x59, 0xa6, 0x70, 0x96, 0x19, 0x9c, 0x65, 0x0e, 0x67, 0x59, 0xc0, 0x59, 0x96, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0xd4, 0x4a, 0xec, 0x76, 0x00, 0x00, 0x00,
}
